### ISSUE TITLE
Incorporate creation of a model from an OSM file instead

### ISSUE THREAD

**Issue by pedrocamargo** [AequilibraE/tradesman#23]
Workflow assumes one would download OSM file from GeoFabrik or equivalent and use OSM2GMNS to create a GMNS network that would be imported into the model instead of using AequilibraE's OSM importer

**Comment by r-akemii** [comment]
@pedrocamargo is this file import like the one existing in AequilibraE?

**Comment by pedrocamargo** [comment]
Related to https://github.com/AequilibraE/aequilibrae/issues/350
