### ISSUE TITLE
Create gallery of Jupyter notebook examples 

### ISSUE THREAD

**Issue by pedrocamargo** [AequilibraE/tradesman#49]
1. [ ] Example of creation of a model from scratch  (possible to do for a tiny country?)
2. [ ] Example (or multiple examples) of different cool visualizations and analysis with a larger model (that is pre-built and stored on Github with releases)

The reference what this will look like is: https://aequilibrae.com/python/latest/_auto_examples/index.html

**Comment by r-akemii** [comment]
- [ ] Add example to import network from osm/pbf file
